### ISSUE TITLE
In Edge: Tweets not updating in tweet panel when move time slider.

### ISSUE THREAD

**Issue by mspruce** [socialsensingbot/frontend#104]
Issue reported by customer using Microsoft Edge to access application (working ok in Chrome):
To replicate try the following:
o   Open tool
o   Click on London
o   Set slider to whole 5 days (be great if tweets updated as you did this)
o   Click out of London in any other county
o   Click back into London
o   Move time slider back to 1 day back from latest time
o   Click out of London in any other county
o   Click back into London and the full 5 days is showing still.

**Comment by neilellis** [comment]
#104 is probably an intermittent rather than browser specific problem. Have created a test to match those exact steps. Have also added a manual refresh button for edge cases. Am trying to reproduce in Edge now.

**Comment by neilellis** [comment]
be great if tweets updated as you did this: **done**

**Comment by neilellis** [comment]
Can no longer reproduce this issue. Have tried many times. Video here:

https://www.dropbox.com/t/cXsBziJakNxk1Gfk
