### ISSUE TITLE
Add new impact column to csv export file. 

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#155]
@rudyarthur : I think they just mean output a blank column in the csv.

**Comment by mspruce** [comment]
Here's more detail on the request by the customer:

csv export file to have a new blank column added with header 'impact level'.  Columns in the export file to be in the following order:
region  |  impact level  |  id  |  date  |  url  |  text

'impact level' is blank by default, however if a user has tagged a tweet with an impact level [https://github.com/socialsensingbot/frontend/issues/156#issue-759847338](url)
then this column would contain whatever impact level has been assigned for the tweet or be blank if no impact level has been assigned.

**Comment by neilellis** [comment]
Blank column added

**Comment by mspruce** [comment]
Impact column should be 2nd column in export file.
