### ISSUE TITLE
Ability to tag tweets with an impact level

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#156]
@rudyarthur : This data be stored as well as coming through in the impact column in the csv export  - Or add the option to tag tweets to the app, in same way as we ignore them

**Comment by mspruce** [comment]
The impact levels that users would like to be able to select from and assign to a tweet in the form of a drop down list (similar to the existing ignore user/tweet function) are as follows: 1 – minimal; 2 – minor; 3 – significant; 4 – severe.  Once a tweet is tagged with one of these options this should be stored in the database and then pulled through into the exported csv file in the new 'impact' column.  For those tweets with no impact category assigned, this field should be blank by default.

**Comment by neilellis** [comment]
Awaiting customer feedback.

**Comment by neilellis** [comment]
From @mspruce on behalf of customer "Import and source columns should be 2nd and 3rd. "
