### ISSUE TITLE
 Users to be able to select text from the tweet without it linking to Twitter 

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#158]
@rudyarthur :  perhaps embed link to Twitter in the tweet header rather than the whole tweet?
 - This is because, for whatever reason, they like to highlight the text of a tweet and copy paste, but when you do that it opens the link to the original tweet. This may be a browser setting on their end! but I guess if it's easy to fix

**Comment by neilellis** [comment]
From the zoom call we decided to show a popup containing the raw text from which they can cut and paste. 

I may be able to do this with a hover action but I suspect it would require a little too much hand eye co-ordination.

**Comment by mspruce** [comment]
This is the original issue logged by the customer if this helps with how to resolve it:

_"Often I want to select a location that is mentioned in the body of the tweet on the social sensing tool. The cursor changes to | to show that I can select the text. When I click to select the text the tweet opens up in Twitter – kind of annoying.
 
Ideal behaviour:
Tweet text is selectable without opening the tweet in Twitter.
The tweet can still be opened by clicking on the tweet header…(perhaps there is a better way than this)."_

**Comment by neilellis** [comment]
Waiting on client feedback.
