### ISSUE TITLE
Hitting 1000 result limit on query

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#159]
Hywel Today at 20:11
From the user: "Just checking the tool this evening a notice that if you hide the tweet and then do a page refresh in the browser the tweet is no longer hidden. It might be designed that way and perhaps we shouldn’t be using the page refresh, but just thought I’d share this. Best if once a tweet has been hidden that it stays hid."

**Comment by neilellis** [comment]
Yes I'm pretty sure I know the problem, there is a limit of 1000 entries I've hit  for queries and the results need to be paginated after that size and I'm not doing that. Will try and produce a fix tomorrow.

The issue is here: https://github.com/aws-amplify/amplify-cli/issues/1496

@Hywel I took a backup first and deleted the first 230 entries (prior to June 2020). This should now behave correctly.

**Comment by neilellis** [comment]
Unlimited results allowed now, data cached locally by AppSync.

**Comment by MuhammadAbdullah54321** [comment]
The limit is still there ....where did you fix it ??
