### ISSUE TITLE
Flagging bad locations

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#164]
In the same way they can flag irrelevant tweets, allow users to flag mis-located tweets. These tweets should be saved for us somewhere so we can improve the location code.

**Comment by neilellis** [comment]
Uploading Screen Recording 2021-05-07 at 17.50.56.mov…

**Comment by mspruce** [comment]
Tested in Chrome and Safari - happy with addition of the 'Mark As' option and including both relevant and mis-located in there.  Happy with this solution.
