### ISSUE TITLE
Time Slider

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#168]
The time slider has been a persistent issue for the clients, particularly making it clear that the latest tweets are showing.

Potential fixes:
 -  Change text when the slider is dragged all the way to the right e.g. it reads “NOW!” or “latest”, or change shape of handle.
 -  Seems to be some issues when dragging it. A lot of computation happens every time the slider moves, apparently sometimes causing erratic behaviour. Could fix by delaying update until mouseup, but this would lose the ability to ‘animate’ the map. However I don’t think anyone uses this...

**Comment by neilellis** [comment]
The flag is animateOnTimeSliderChange and can be found in https://github.com/socialsensingbot/frontend/blob/release/1.5/src/environments/environment.ts - the end date is now.

**Comment by neilellis** [comment]
Creating a separate issue to deal with live updating of tweets.
