### ISSUE TITLE
New tweet highlight

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#169]
Highlight counties (coloured border?) which had a new tweet in past hour.

**Comment by neilellis** [comment]
https://user-images.githubusercontent.com/710307/117469192-5a76a680-af4d-11eb-8147-4c508d7a3916.mov

**Comment by neilellis** [comment]
The variable in environment.ts is recentTweetHighlightOffsetInSeconds

**Comment by mspruce** [comment]
Tested in Chrome and Safari - like the grey border, however flashing is too fast - suggest slowing down the frequency of the flashing, perhaps once every 5s?  Might need to see a couple of options for the flashing.  Also could the time window for flashing be set to 1 hour (i.e. 3600 secs)?  May want to amend this following customer feedback.
Also - suggest the flashing stops if 'now' is not selected on the time slider, if possible.

**Comment by neilellis** [comment]
The blinking behaviour needs to be infinite however it only blinks if there have been new tweets. The period for this is set in the preference recentTweetHighlightOffsetInSeconds

**Comment by neilellis** [comment]
https://user-images.githubusercontent.com/710307/118155221-e6864380-b40f-11eb-8eec-c2ac00720088.mov

**Comment by neilellis** [comment]
Now only shows when doing 'live' updating. Added (live) text after date range if it is showing 'live' data (i.e. auto-updating)

**Comment by neilellis** [comment]
![image](https://user-images.githubusercontent.com/710307/118163012-5a791980-b419-11eb-94a5-fe6e08cfc817.png)

**Comment by mspruce** [comment]
> Okay 5 seconds was a bit too long I felt, how does this look? :
> 
>  Screen.Recording.2021-05-13.at.17.22.37.mov

Yes that rate of blinking looks good to me.  And thumbs up for only showing when 'live updating'.

**Comment by mspruce** [comment]
> The CSS blinking behaviour needs to be infinite, however the CSS class is only applied when there have been new tweets. The period for this is set in the preference recentTweetHighlightOffsetInSeconds (deault is 20 minutes)

I've a feeling the customer are going to ask if the blinking can cease if they've read/clicked the county to see the new tweets...and then only start to blink again if there have been new tweets since they last clicked on that county and looked at the tweets...not sure if this is going to be possible if the CSS blinking behaviour needs to be infinite?  However we could just release as it is and await their feedback.

**Comment by mspruce** [comment]
Feedback from customer: they like the idea of the new tweet indicator and have said they are happy for it to be released as it is and feed back how they find it (e.g. on floody days where the whole map is likely to be flashing!).  They did mention if the blinking could cease if they click on the county and look at the new tweets....so one to think about.

**Comment by neilellis** [comment]
Great.
