### ISSUE TITLE
Export countries

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#170]
Should be a way to export all of England, all of Wales, all of England and Wales (tick boxes?)

**Comment by neilellis** [comment]
I'm thinking this should be a feature for any map location, so a general aggregation of regions, does that make sense?

**Comment by rudyarthur** [comment]
[locales.zip](https://github.com/socialsensingbot/frontend/files/6376607/locales.zip)

**Comment by neilellis** [comment]
On the global download menu you can now choose to download by country, do you think that will suffice @rudyarthur ?

**Comment by neilellis** [comment]
![image](https://user-images.githubusercontent.com/710307/117058148-30876f00-ad16-11eb-8ab6-81962031ca2e.png)

**Comment by neilellis** [comment]
Will change to multiselect

**Comment by neilellis** [comment]
Changed to multiselect, still not completely happy will await feedback.

**Comment by neilellis** [comment]
https://user-images.githubusercontent.com/710307/117323214-9a268b00-ae86-11eb-996d-1cb13c57e108.mov

**Comment by mspruce** [comment]
Tested in Chrome and Safari - all working well - happy with this solution.
