### ISSUE TITLE
Options for 'source'

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#173]
The client requested to leave this blank so they could fill in the csv. If there are a finite number of options could work same way impact tagging does. (would also be useful data for us to collect for potential ML service)

**Comment by neilellis** [comment]
Are you intending to obtain the fixed set of values and should this go into 1.5

**Comment by rudyarthur** [comment]
Apparently we have it already, I will dig it up

**Comment by rudyarthur** [comment]
The options are: river, surface, groundwater, coastal

**Comment by neilellis** [comment]
Fab thanks @rudyarthur !

**Comment by mspruce** [comment]
Tested in Chrome and Safari - Selection of source looks good - however when you select a source, it clears the impact and vice versa if you then select an impact, it clears the source - need to be able to have both selected as well as one or the other.

**Comment by mspruce** [comment]
This all appears to be working as it should now.  Customer also happy, so this issue can be closed.
