### ISSUE TITLE
Export time frame

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#174]
User feedback
 
"Although you can filter the time, the downloaded csv sometimes includes times other than the time frame you have set."

Check this

**Comment by neilellis** [comment]
Oh this one is going to be fun :-)

I use .toUTCString()

![image](https://user-images.githubusercontent.com/710307/115060256-9040e600-9edf-11eb-810e-606f3437700f.png)

It annoyingly says GMT not UTC but is UTC of course.

I set the URL as so :-

https://app.socialsensing.com/map?active_number=stats&active_polygon=county&max_time=1618589520000&min_time=1618582320000

And indeed I got one tweet too many 


region | impact | source | id | date | url | text |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Greater   Manchester |   | 1.38309E+18 | Fri, 16 Apr 2021 16:02:00 GMT | https://twitter.com/username_removed/status/1383088534400204803 | Thank you @USERNAME_REMOVED wow my   childhood came flooding back today couldn't get any better.
Derbyshire |   | 1.38307E+18 | Fri, 16 Apr 2021 14:40:00 GMT | https://twitter.com/username_removed/status/1383067895115223042 | This is the first time my socials   have been flooded with parents getting their children’s school places   accepted 😳

**Comment by neilellis** [comment]
Using https://www.epochconverter.com/ I checked the timestamp in our URL and 

1618582320 is Friday, 16 April 2021 14:12:00 GMT or Friday, 16 April 2021 15:12:00 **DST**

**Comment by neilellis** [comment]
This is obviously happening as the time slider is set to increments of one hour ago and the time I did that it was 12 minutes past the hour. This is why it is sometimes getting extra tweets or missing tweets and sometimes not.

So I suspect that I need to do increments of 1 hour rounded to 1 hour with an additional step of **NOW**.
