### ISSUE TITLE
When scrolled to *now* in the date time slider continuously update data

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#178]

**Comment by neilellis** [comment]
The environment.ts file now includes a continuousUpdateThresholdInSeconds property. If the time of the slider is within this amount then the time slider will 'stick' at now rather than moving with the time. If the slider is greater than this the time range is preserved and the scrolls to the left as time progresses.

**Comment by neilellis** [comment]
The URL is also updated so that the max_time reflects the latest time in the current data set (i.e. now) - this means the URL can be shared and if it's older than  continuousUpdateThresholdInMinutes it will remain static if it's more recent it will also stick at 'now'.

**Comment by mspruce** [comment]
Tested in Chrome and Safari - appears to be working correctly, however need to test on live data ideally - so will have to come back to this one when moved to staging.

**Comment by neilellis** [comment]
Added support for live data in development :- 
![image](https://user-images.githubusercontent.com/710307/118139569-648e1e80-b3ff-11eb-8100-0670b3ffc208.png)

**Comment by neilellis** [comment]
![image](https://user-images.githubusercontent.com/710307/118200712-b2ca0e80-b44d-11eb-9405-9d5169f95c33.png)

**Comment by mspruce** [comment]
This is a nice addition which makes clear to the user that it is 'live updating'.
