### ISSUE TITLE
Make the colour bar when a tweet is tagged with an impact more visible

### ISSUE THREAD

**Issue by mspruce** [socialsensingbot/frontend#193]
![Screenshot 2021-05-25 at 14 22 26](https://user-images.githubusercontent.com/33754358/119505294-b66e6700-bd64-11eb-80b3-53a7953ca66f.png)

Could the colour bar be made thicker so that it is more visible?

I've added to 1.5, but could be a 1.5.1 if not a quick fix.

**Comment by neilellis** [comment]
Putting this in 1.5.1
