### ISSUE TITLE
Exceedence calculation is a resource hog

### ISSUE THREAD

**Issue by rudyarthur** [socialsensingbot/frontend#205]

**Comment by rudyarthur** [comment]
Can fix this with 2 changes: 
1. 'run length encode' the stats files. So this kind of thing 
"aberdeen city":[0,0,0,0,0,0,0,.....]
becomes
"aberdeen city": {"0": 1129, "1": 127, "2": 39, "3": 13, "4": 9, "5": 2, "6": 3, "7": 2, "8": 1, "9": 2, "10": 1, "11": 2, "12": 2, "
13": 1, "19": 1, "37": 1, "109": 1}

2. The getStatsIdx function becomes 

getStatsIdx(place: string, val: number, stats: Stats): number {

    keys = Object.keys(stats[this._region.id][place]),
    i, len = keys.length;
    keys.sort();

    let acc = 0;
    for (let i = 0; i < len; i++) {
      k = keys[i]
     
      if (val <= Math.round(k)) {
        return acc;
      }

      acc += stats[this._region.id][place][  k   ]

    }
    return len;
  }

**Comment by rudyarthur** [comment]
The sort step in 2. is obviously silly. I don't know how to handle sorted dictionaries in javascript. Could even be a list of pairs if that's easier? 

In anycase this should be about 100 faster

**Comment by neilellis** [comment]
I did implement the changes but they are now redundant as of 2.2
