### ISSUE TITLE
Analytics - default 'All' to 'All UK'

### ISSUE THREAD

**Issue by mspruce** [socialsensingbot/frontend#284]
Customer request: Please can default plot in analytics be All UK (i.e. excluding Republic of Ireland) instead of 'All'.
As well as changing default data, also change label to 'All UK' to avoid any ambiguity.

**Comment by mspruce** [comment]
Added to 2.2 milestone to possibly include in next release?

**Comment by neilellis** [comment]
Have implemented UK, Great Britain and British Isles as level 3 (country) level aggregations and they include the correct regions. The default region can now be set in preferences 

```analyticsDefaultRegions:      ["uk"]```
