### ISSUE TITLE
Region selection box on Analytics

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#310]
@rudyarthur : In the region select on the Analytics page, can we group the regions in size order and alphabetical within their group e.g.
```
England
Northern Ireland
Republic of Ireland
Scotland
Wales
----------------
South East England
South West England
...
-----------------
Aberdeen
....
```

**Comment by mspruce** [comment]
The options at the top of the dropdown look a bit strange and there are duplicates. Probably want it to start with United Kingdom and Ireland, then the UK countries (England, Scotland, etc), then the UK regions (North West, South West, etc), if this is possible?
![image](https://user-images.githubusercontent.com/33754358/142192788-baf7b975-bed9-4cd3-9446-f8e6c0e3ea38.png)
![image](https://user-images.githubusercontent.com/33754358/142192824-3f3027ac-460f-446b-99b7-d033760ddb33.png)
![image](https://user-images.githubusercontent.com/33754358/142192851-a90703ee-f0fe-4f4b-9232-f6ff3e5974ce.png)

**Comment by mspruce** [comment]
![image](https://user-images.githubusercontent.com/33754358/142193288-88c7e1b1-42ed-4f75-a4ca-0a7346f1540c.png)
