### ISSUE TITLE
Logo Image and/or favicon

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#33]

**Comment by neilellis** [comment]
If you can't provide this I can produce one for you.

**Comment by neilellis** [comment]
![image](https://user-images.githubusercontent.com/710307/80222066-2c723d00-863e-11ea-883b-4d30396c67e3.png)

**Comment by mspruce** [comment]
Hi Neil - I've created an EPS version - does this look ok at your end?
[Social Sensing-cropped.eps.zip](https://github.com/socialsensingbot/frontend/files/4529625/Social.Sensing-cropped.eps.zip)

**Comment by neilellis** [comment]
It seems to be a single bitmap object I'm afraid. What app did you edit this in?

**Comment by neilellis** [comment]
If necc. I can reproduce this in a vector graphic editor. So please don't worry too much!

**Comment by mspruce** [comment]
I used Inkscape.  But I'm a bit of a novice I'll admit.  I have a pdf version (attached now) which might be easier for you to work with?  Sorry!
[Social Sensing-cropped.pdf](https://github.com/socialsensingbot/frontend/files/4529702/Social.Sensing-cropped.pdf)

**Comment by mspruce** [comment]
I used Inkscape - but I'm a bit of a novice.  I have a pdf version which you might find easier to work with?  But it needs cropping. Sorry!
[Social Sensing.pdf](https://github.com/socialsensingbot/frontend/files/4529709/Social.Sensing.pdf)

**Comment by neilellis** [comment]
Hey no problem Michelle, I'll give that a shot and if not I'll just trace over the png/pdf version in my vector editor.

**Comment by neilellis** [comment]
Yep that worked, the images I've used will be in the /graphics folder when this PR gets merged. And the icons will be in /src (live favicons etc.) /assets/icon-white  /assets/icon-color for the UI versions.
