### ISSUE TITLE
FFC: Add "today" and "yesterday" as options in the time window menu?

### ISSUE THREAD

**Issue by neilellis** [socialsensingbot/frontend#376]
How easy to add "today" and "yesterday" as options in the time window menu? i.e. the window would run from midnight to midnight.

**Comment by mspruce** [comment]
https://user-images.githubusercontent.com/33754358/149165906-759fbaa3-0c4d-4396-b6e3-ad6c857ff9bc.mp4

Just testing the 'Today' and 'Yesterday' time selector in Chrome (I cleared cache first). It's a bit glitchy. Attached video shows that end time for yesterday not updating. 
Not shown in video as struggling to replicate, but also, sometimes if you flick between Yesterday and Today, it does update the end time for for Yesterday, but then when you switch back to today it keeps the end time as yesterday's end time. 
So please could you take another look? Thank you!
