### ISSUE TITLE
Export tweets function

### ISSUE THREAD

**Issue by mspruce** [socialsensingbot/frontend#83]
TO HOLD OFF ON THIS WHILE CUSTOMER DISCUSSES INTERNALLY HOWEVER WE NEED TO EXPLORE THE POSSIBILITIES FOR THIS OPTION: Customer would like to be able to click a county, hide unwanted tweets, label tweets with impact level and then export the tweet content including County name, Date/time of tweet, Tweet text, Tweet url, level of impact -> export to a format that can be read in MS Excel (e.g. csv, txt, xlsx, etc) - need to be mindful of Twitter TOCs

**Comment by mspruce** [comment]
Required: Customer clicks on county/grid box.
Set time slider to desired timescale.
Hide tweets/users not relevant.
Click 'export' button - within tweet box.
This will export a csv file of the following: County/co-ordinates of grid box, url to tweet, Tweet ID, Timestamp, Tweet Text

**Comment by neilellis** [comment]
The full timestamp is not currently available to be @rudyarthur @mspruce I have only the time slice at present. LMK if that is the time resolution required.

**Comment by mspruce** [comment]
Time slice is fine.

**Comment by neilellis** [comment]
Tweet text or Tweet HTML?

**Comment by neilellis** [comment]
In env: https://feature-frontend-83.dtmxl3q3i7oix.amplifyapp.com/
