### ISSUE TITLE
Hidden tweets reappearing after refresh

### ISSUE THREAD

**Issue by mspruce** [socialsensingbot/frontend#87]
Hidden tweets reappear after page is refreshed.  Hidden users remain hidden.

**Comment by neilellis** [comment]
The requirement I had was that tweets are hidden on a per user basis. Are we saying otherwise?

**Comment by neilellis** [comment]
Seperating that out to a seperate issue #88

**Comment by mspruce** [comment]
If that was in the original spec then don't worry - keep it as tweets hidden on a per user basis.  I wasn't aware that this was what requested.  I'll amend this issue to just look the hidden tweets displaying bug.

**Comment by neilellis** [comment]
Great I'll leave you/rudy/hywel to figure out if #88 is expected behaviour.

**Comment by neilellis** [comment]
Test written and fix ready https://feature-frontend-87.dtmxl3q3i7oix.amplifyapp.com/map
